export type Applicant = {
  areasOfInterest: string | null;
  branch: string | null;
  createdAt: Date;
  currentClubMemberships: string | null;
  email: string | null;
  expectations: string | null;
  fullName: string | null;
  gitHubProfile: string | null;
  id: string;
  linkedInProfile: string | null;
  motivation: string | null;
  phoneNumber: number | null;
  preferredDepartment: string | null;
  previousProjects: string | null;
  referral: string | null;
  registrationNumber: string | null;
  technicalSkills: string | null;
  updatedAt: Date;
  year: number | null;
};
